distance_collision_operations:
  - object1: arm
    object2: arm
    operation: disable

default_collision_operations:
  - object1: base_footprint
    object2: base_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: arm_link_0
    operation: disable  # Adjacent in collision
  - object1: arm_link_0
    object2: arm_link_1
    operation: disable  # Adjacent in collision
  - object1: arm_link_1
    object2: arm_link_2
    operation: disable  # Adjacent in collision
  - object1: arm_link_2
    object2: arm_link_3
    operation: disable  # Adjacent in collision
  - object1: arm_link_3
    object2: arm_link_4
    operation: disable  # Adjacent in collision
  - object1: arm_link_4
    object2: arm_link_5
    operation: disable  # Adjacent in collision
  - object1: arm_link_5
    object2: gripper_palm_link
    operation: disable  # Adjacent in collision
  - object1: gripper_palm_link
    object2: gripper_finger_link_l
    operation: disable  # Adjacent in collision
  - object1: gripper_palm_link
    object2: gripper_finger_link_r
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: base_laser_front_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: base_laser_rear_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_bl
    operation: disable  # Adjacent in collision
  - object1: caster_link_bl
    object2: wheel_link_bl
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_br
    operation: disable  # Adjacent in collision
  - object1: caster_link_br
    object2: wheel_link_br
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_fl
    operation: disable  # Adjacent in collision
  - object1: caster_link_fl
    object2: wheel_link_fl
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_fr
    operation: disable  # Adjacent in collision
  - object1: caster_link_fr
    object2: wheel_link_fr
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: plate_link
    operation: disable  # Adjacent in collision
  - object1: plate_link
    object2: tower_link
    operation: disable  # Adjacent in collision
  - object1: tower_link
    object2: openni_camera
    operation: disable  # Adjacent in collision
  - object1: openni_camera
    object2: openni_depth_frame
    operation: disable  # Adjacent in collision
  - object1: openni_depth_frame
    object2: openni_depth_optical_frame
    operation: disable  # Adjacent in collision
  - object1: openni_camera
    object2: openni_rgb_frame
    operation: disable  # Adjacent in collision
  - object1: openni_rgb_frame
    object2: openni_rgb_optical_frame
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: wheel_link_bl
    operation: disable  # Always in collision
  - object1: base_link
    object2: wheel_link_br
    operation: disable  # Always in collision
  - object1: base_link
    object2: wheel_link_fl
    operation: disable  # Always in collision
  - object1: base_link
    object2: wheel_link_fr
    operation: disable  # Always in collision
  - object1: arm_link_0
    object2: arm_link_2
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: plate_link
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: tower_link
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: plate_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: tower_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: plate_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: tower_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: tower_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: tower_link
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: tower_link
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: plate_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: tower_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: base_laser_rear_link
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: plate_link
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: tower_link
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: plate_link
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: tower_link
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: base_laser_rear_link
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: base_link
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: base_link
    object2: tower_link
    operation: disable  # Never in collision
  - object1: gripper_finger_link_l
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: gripper_finger_link_l
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: gripper_finger_link_r
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: gripper_palm_link
    object2: openni_camera
    operation: disable  # Never in collision
  - object1: openni_camera
    object2: plate_link
    operation: disable  # Never in collision
  - object1: openni_camera
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: openni_camera
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: openni_camera
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: openni_camera
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: tower_link
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: tower_link
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: tower_link
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: tower_link
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: wheel_link_bl
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: wheel_link_bl
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: wheel_link_bl
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: wheel_link_br
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: wheel_link_br
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: wheel_link_fl
    object2: wheel_link_fr
    operation: disable  # Never in collision
