map_type: costmap
#transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.26, 0.18],[0.26, 0.014],[0.31, 0.014],[0.31, -0.014],[0.26, -0.014],[0.26, -0.18],[-0.27, -0.18],[-0.27, 0.18]]

#Footprint with rear laser scanner
#footprint: [[0.26, 0.18],[0.26, 0.014],[0.31, 0.014],[0.31, -0.014],[0.26, -0.014],[0.26, -0.18],[-0.27, -0.18],[-0.27,-0.014],[-0.32,-0.014],
#[-0.32,0.014],[-0.27,0.014],[-0.27, 0.18]]

inflation_radius: 0.36
observation_sources: laser_scanner_front

laser_scanner_front: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: /scan_front, expected_update_rate: 0.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}

